const fs = require('node:fs')
const path = require('node:path')

const iconNodesPath = path.join(__dirname, '../node_modules/lucide-static/icon-nodes.json')
const outputPath = path.join(__dirname, '../icons.d.ts')

try {
  // Read the icon nodes JSON
  const iconNodes = JSON.parse(fs.readFileSync(iconNodesPath, 'utf-8'))

  // Get all icon names
  const iconNames = Object.keys(iconNodes)

  // Generate the TypeScript union type
  const iconType = iconNames.map(name => `  | '${name}'`).join('\n')

  // Generate the file content
  const content = `// Auto-generated from lucide-static
// Do not edit this file manually

export type IconName =
${iconType}
`

  // Write the file
  fs.writeFileSync(outputPath, content)

  console.log(`✓ Generated ${iconNames.length} icon types in icons.d.ts`)
} catch (error) {
  console.error('Error generating icon types:', error.message)
  process.exit(1)
}
